//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streetcode.XUnitTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Streetcode.XUnitTest.TestMessages", typeof(TestMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert null to news.
        /// </summary>
        internal static string CannotConvertNullToNews {
            get {
                return ResourceManager.GetString("CannotConvertNullToNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert null to streetcodeCoordinate.
        /// </summary>
        internal static string CannotConvertNullToStreetcodeCoordinate {
            get {
                return ResourceManager.GetString("CannotConvertNullToStreetcodeCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert null to team link.
        /// </summary>
        internal static string CannotConvertNullToTeamLink {
            get {
                return ResourceManager.GetString("CannotConvertNullToTeamLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create DTOs for related words!.
        /// </summary>
        internal static string CannotCreateDtosForRelatedWords {
            get {
                return ResourceManager.GetString("CannotCreateDtosForRelatedWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create new related word for a term!.
        /// </summary>
        internal static string CannotCreateNewRelatedWordForTerm {
            get {
                return ResourceManager.GetString("CannotCreateNewRelatedWordForTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create team link.
        /// </summary>
        internal static string CannotCreateTeamLink {
            get {
                return ResourceManager.GetString("CannotCreateTeamLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find an art with corresponding id: {0}.
        /// </summary>
        internal static string CannotFindAnArtWithCorrespondingId {
            get {
                return ResourceManager.GetString("CannotFindAnArtWithCorrespondingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find an audio with corresponding categoryId: {0}.
        /// </summary>
        internal static string CannotFindAnAudioWithCorrespondingCategoryId {
            get {
                return ResourceManager.GetString("CannotFindAnAudioWithCorrespondingCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find an audio with corresponding id: {0}.
        /// </summary>
        internal static string CannotFindAnAudioWithCorrespondingId {
            get {
                return ResourceManager.GetString("CannotFindAnAudioWithCorrespondingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find an audio with the corresponding streetcode id: {0}.
        /// </summary>
        internal static string CannotFindAnAudioWithCorrespondingStreetcodeId {
            get {
                return ResourceManager.GetString("CannotFindAnAudioWithCorrespondingStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any arts.
        /// </summary>
        internal static string CannotFindAnyArts {
            get {
                return ResourceManager.GetString("CannotFindAnyArts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any art with corresponding streetcode id: {0}.
        /// </summary>
        internal static string CannotFindAnyArtWithCorrespondingStreetcodeId {
            get {
                return ResourceManager.GetString("CannotFindAnyArtWithCorrespondingStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any audios.
        /// </summary>
        internal static string CannotFindAnyAudios {
            get {
                return ResourceManager.GetString("CannotFindAnyAudios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any partners.
        /// </summary>
        internal static string CannotFindAnyPartners {
            get {
                return ResourceManager.GetString("CannotFindAnyPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any partners with corresponding streetcode id: {0}.
        /// </summary>
        internal static string CannotFindAnyPartnersWithCorrespondingStreetcodeId {
            get {
                return ResourceManager.GetString("CannotFindAnyPartnersWithCorrespondingStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any partner with corresponding id: {0}.
        /// </summary>
        internal static string CannotFindAnyPartnerWithCorrespondingId {
            get {
                return ResourceManager.GetString("CannotFindAnyPartnerWithCorrespondingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any positions.
        /// </summary>
        internal static string CannotFindAnyPositions {
            get {
                return ResourceManager.GetString("CannotFindAnyPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any subtitles.
        /// </summary>
        internal static string CannotFindAnySubtitles {
            get {
                return ResourceManager.GetString("CannotFindAnySubtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any tag by the streetcode id: {0}.
        /// </summary>
        internal static string CannotFindAnyTagByStreetcodeId {
            get {
                return ResourceManager.GetString("CannotFindAnyTagByStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any tag by the title: {0}.
        /// </summary>
        internal static string CannotFindAnyTagByTitle {
            get {
                return ResourceManager.GetString("CannotFindAnyTagByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any tags.
        /// </summary>
        internal static string CannotFindAnyTags {
            get {
                return ResourceManager.GetString("CannotFindAnyTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any team.
        /// </summary>
        internal static string CannotFindAnyTeam {
            get {
                return ResourceManager.GetString("CannotFindAnyTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any team links.
        /// </summary>
        internal static string CannotFindAnyTeamLinks {
            get {
                return ResourceManager.GetString("CannotFindAnyTeamLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any team with corresponding id: {0}.
        /// </summary>
        internal static string CannotFindAnyTeamWithCorrespondingId {
            get {
                return ResourceManager.GetString("CannotFindAnyTeamWithCorrespondingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any timelineItem.
        /// </summary>
        internal static string CannotFindAnyTimelineItem {
            get {
                return ResourceManager.GetString("CannotFindAnyTimelineItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any timeline item by the streetcode id: {0}.
        /// </summary>
        internal static string CannotFindAnyTimelineItemByStreetcodeId {
            get {
                return ResourceManager.GetString("CannotFindAnyTimelineItemByStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a coordinates by a streetcode id: {0}.
        /// </summary>
        internal static string CannotFindCoordinatesByStreetcodeId {
            get {
                return ResourceManager.GetString("CannotFindCoordinatesByStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a coordinates by a streetcode id: {0}, because such streetcode doesn`t exist.
        /// </summary>
        internal static string CannotFindCoordinatesByStreetcodeIdBecauseStreetcodeDoesNotExist {
            get {
                return ResourceManager.GetString("CannotFindCoordinatesByStreetcodeIdBecauseStreetcodeDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a coordinate with corresponding categoryId: {0}.
        /// </summary>
        internal static string CannotFindCoordinateWithCorrespondingCategoryId {
            get {
                return ResourceManager.GetString("CannotFindCoordinateWithCorrespondingCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a partners by a streetcode id: {0}.
        /// </summary>
        internal static string CannotFindPartnersByStreetcodeId {
            get {
                return ResourceManager.GetString("CannotFindPartnersByStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a related term: {0} for term with id: {1}.
        /// </summary>
        internal static string CannotFindRelatedTerm {
            get {
                return ResourceManager.GetString("CannotFindRelatedTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a subtitle with corresponding id: {0}.
        /// </summary>
        internal static string CannotFindSubtitleWithCorrespondingId {
            get {
                return ResourceManager.GetString("CannotFindSubtitleWithCorrespondingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a Tag with corresponding id: {0}.
        /// </summary>
        internal static string CannotFindTagWithCorrespondingId {
            get {
                return ResourceManager.GetString("CannotFindTagWithCorrespondingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a timeline item with corresponding id: {0}.
        /// </summary>
        internal static string CannotFindTimelineItemWithCorrespondingId {
            get {
                return ResourceManager.GetString("CannotFindTimelineItemWithCorrespondingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get words by term id.
        /// </summary>
        internal static string CannotGetWordsByTermId {
            get {
                return ResourceManager.GetString("CannotGetWordsByTermId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot map entity!.
        /// </summary>
        internal static string CannotMapEntity {
            get {
                return ResourceManager.GetString("CannotMapEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save changes in the database after creation.
        /// </summary>
        internal static string CannotSaveChangesAfterCreation {
            get {
                return ResourceManager.GetString("CannotSaveChangesAfterCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save changes in the database after related word creation!.
        /// </summary>
        internal static string CannotSaveChangesAfterRelatedWordCreation {
            get {
                return ResourceManager.GetString("CannotSaveChangesAfterRelatedWordCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection lost.
        /// </summary>
        internal static string DatabaseConnectionLost {
            get {
                return ResourceManager.GetString("DatabaseConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database error.
        /// </summary>
        internal static string DatabaseError {
            get {
                return ResourceManager.GetString("DatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database error during update.
        /// </summary>
        internal static string DatabaseErrorDuringUpdate {
            get {
                return ResourceManager.GetString("DatabaseErrorDuringUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB save failed.
        /// </summary>
        internal static string DatabaseSaveFailed {
            get {
                return ResourceManager.GetString("DatabaseSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionStrings:DefaultConnection.
        /// </summary>
        internal static string DefaultConnectionConfigurationKey {
            get {
                return ResourceManager.GetString("DefaultConnectionConfigurationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteAudioCommand handled successfully.
        /// </summary>
        internal static string DeleteAudioCommandHandledSuccessfully {
            get {
                return ResourceManager.GetString("DeleteAudioCommandHandledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create an audio.
        /// </summary>
        internal static string FailedToCreateAnAudio {
            get {
                return ResourceManager.GetString("FailedToCreateAnAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a news.
        /// </summary>
        internal static string FailedToCreateNews {
            get {
                return ResourceManager.GetString("FailedToCreateNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a streetcodeCoordinate.
        /// </summary>
        internal static string FailedToCreateStreetcodeCoordinate {
            get {
                return ResourceManager.GetString("FailedToCreateStreetcodeCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a team.
        /// </summary>
        internal static string FailedToCreateTeam {
            get {
                return ResourceManager.GetString("FailedToCreateTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete an audio.
        /// </summary>
        internal static string FailedToDeleteAnAudio {
            get {
                return ResourceManager.GetString("FailedToDeleteAnAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete a coordinate.
        /// </summary>
        internal static string FailedToDeleteCoordinate {
            get {
                return ResourceManager.GetString("FailedToDeleteCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete news.
        /// </summary>
        internal static string FailedToDeleteNews {
            get {
                return ResourceManager.GetString("FailedToDeleteNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete a related term.
        /// </summary>
        internal static string FailedToDeleteRelatedTerm {
            get {
                return ResourceManager.GetString("FailedToDeleteRelatedTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update news.
        /// </summary>
        internal static string FailedToUpdateNews {
            get {
                return ResourceManager.GetString("FailedToUpdateNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update a streetcodeCoordinate.
        /// </summary>
        internal static string FailedToUpdateStreetcodeCoordinate {
            get {
                return ResourceManager.GetString("FailedToUpdateStreetcodeCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection string &apos;ConnectionStrings:DefaultConnection&apos; is missing. Set &apos;STREETCODE_ConnectionStrings__DefaultConnection&apos; in the environment or .env file..
        /// </summary>
        internal static string MissingDefaultConnectionString {
            get {
                return ResourceManager.GetString("MissingDefaultConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No news by entered Id - {0}.
        /// </summary>
        internal static string NoNewsByEnteredId {
            get {
                return ResourceManager.GetString("NoNewsByEnteredId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No news by entered Url - {0}.
        /// </summary>
        internal static string NoNewsByEnteredUrl {
            get {
                return ResourceManager.GetString("NoNewsByEnteredUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No news found by entered Id - {0}.
        /// </summary>
        internal static string NoNewsFoundByEnteredId {
            get {
                return ResourceManager.GetString("NoNewsFoundByEnteredId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No partner with such id.
        /// </summary>
        internal static string NoPartnerWithSuchId {
            get {
                return ResourceManager.GetString("NoPartnerWithSuchId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слово з цим визначенням уже існує.
        /// </summary>
        internal static string RelatedWordAlreadyExists {
            get {
                return ResourceManager.GetString("RelatedWordAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A term with the title &apos;{0}&apos; already exists..
        /// </summary>
        internal static string TermWithTitleAlreadyExists {
            get {
                return ResourceManager.GetString("TermWithTitleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no news in the database.
        /// </summary>
        internal static string ThereAreNoNewsInDatabase {
            get {
                return ResourceManager.GetString("ThereAreNoNewsInDatabase", resourceCulture);
            }
        }
    }
}
