//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the StronglyTypedResourceBuilder.
//     Changes to this file may be lost if the resource is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streetcode.XUnitTest;

using System.Globalization;
using System.Resources;

internal static class TestMessages
{
    private static readonly ResourceManager ResourceManager =
        new("Streetcode.XUnitTest.TestMessages", typeof(TestMessages).Assembly);

    private static string GetString(string name) =>
        ResourceManager.GetString(name, CultureInfo.InvariantCulture)!;

    internal static string CannotConvertNullToNews => GetString(nameof(CannotConvertNullToNews));
    internal static string CannotConvertNullToStreetcodeCoordinate => GetString(nameof(CannotConvertNullToStreetcodeCoordinate));
    internal static string CannotConvertNullToTeamLink => GetString(nameof(CannotConvertNullToTeamLink));
    internal static string CannotCreateTeamLink => GetString(nameof(CannotCreateTeamLink));
    internal static string CannotCreateDtosForRelatedWords => GetString(nameof(CannotCreateDtosForRelatedWords));
    internal static string CannotCreateNewRelatedWordForTerm => GetString(nameof(CannotCreateNewRelatedWordForTerm));
    internal static string CannotFindAnArtWithCorrespondingId => GetString(nameof(CannotFindAnArtWithCorrespondingId));
    internal static string CannotFindAnAudioWithCorrespondingCategoryId => GetString(nameof(CannotFindAnAudioWithCorrespondingCategoryId));
    internal static string CannotFindAnAudioWithCorrespondingId => GetString(nameof(CannotFindAnAudioWithCorrespondingId));
    internal static string CannotFindAnAudioWithCorrespondingStreetcodeId => GetString(nameof(CannotFindAnAudioWithCorrespondingStreetcodeId));
    internal static string CannotFindAnySubtitles => GetString(nameof(CannotFindAnySubtitles));
    internal static string CannotFindAnyTagByStreetcodeId => GetString(nameof(CannotFindAnyTagByStreetcodeId));
    internal static string CannotFindAnyTagByTitle => GetString(nameof(CannotFindAnyTagByTitle));
    internal static string CannotFindAnyTags => GetString(nameof(CannotFindAnyTags));
    internal static string CannotFindAnyTimelineItem => GetString(nameof(CannotFindAnyTimelineItem));
    internal static string CannotFindAnyTimelineItemByStreetcodeId => GetString(nameof(CannotFindAnyTimelineItemByStreetcodeId));
    internal static string CannotFindAnyArts => GetString(nameof(CannotFindAnyArts));
    internal static string CannotFindAnyArtWithCorrespondingStreetcodeId => GetString(nameof(CannotFindAnyArtWithCorrespondingStreetcodeId));
    internal static string CannotFindAnyAudios => GetString(nameof(CannotFindAnyAudios));
    internal static string CannotFindAnyPartners => GetString(nameof(CannotFindAnyPartners));
    internal static string CannotFindAnyPartnersWithCorrespondingStreetcodeId => GetString(nameof(CannotFindAnyPartnersWithCorrespondingStreetcodeId));
    internal static string CannotFindAnyPartnerWithCorrespondingId => GetString(nameof(CannotFindAnyPartnerWithCorrespondingId));
    internal static string CannotFindAnyPositions => GetString(nameof(CannotFindAnyPositions));
    internal static string CannotFindAnyTeam => GetString(nameof(CannotFindAnyTeam));
    internal static string CannotFindAnyTeamLinks => GetString(nameof(CannotFindAnyTeamLinks));
    internal static string CannotFindAnyTeamWithCorrespondingId => GetString(nameof(CannotFindAnyTeamWithCorrespondingId));
    internal static string CannotFindPartnersByStreetcodeId => GetString(nameof(CannotFindPartnersByStreetcodeId));
    internal static string CannotFindCoordinatesByStreetcodeId => GetString(nameof(CannotFindCoordinatesByStreetcodeId));
    internal static string CannotFindCoordinatesByStreetcodeIdBecauseStreetcodeDoesNotExist => GetString(nameof(CannotFindCoordinatesByStreetcodeIdBecauseStreetcodeDoesNotExist));
    internal static string CannotFindCoordinateWithCorrespondingCategoryId => GetString(nameof(CannotFindCoordinateWithCorrespondingCategoryId));
    internal static string CannotFindRelatedTerm => GetString(nameof(CannotFindRelatedTerm));
    internal static string CannotFindSubtitleWithCorrespondingId => GetString(nameof(CannotFindSubtitleWithCorrespondingId));
    internal static string CannotFindTagWithCorrespondingId => GetString(nameof(CannotFindTagWithCorrespondingId));
    internal static string CannotFindTimelineItemWithCorrespondingId => GetString(nameof(CannotFindTimelineItemWithCorrespondingId));
    internal static string CannotGetWordsByTermId => GetString(nameof(CannotGetWordsByTermId));
    internal static string CannotMapEntity => GetString(nameof(CannotMapEntity));
    internal static string CannotSaveChangesAfterCreation => GetString(nameof(CannotSaveChangesAfterCreation));
    internal static string CannotSaveChangesAfterRelatedWordCreation => GetString(nameof(CannotSaveChangesAfterRelatedWordCreation));
    internal static string DatabaseConnectionLost => GetString(nameof(DatabaseConnectionLost));
    internal static string DatabaseError => GetString(nameof(DatabaseError));
    internal static string DatabaseErrorDuringUpdate => GetString(nameof(DatabaseErrorDuringUpdate));
    internal static string DatabaseSaveFailed => GetString(nameof(DatabaseSaveFailed));
    internal static string DefaultConnectionConfigurationKey => GetString(nameof(DefaultConnectionConfigurationKey));
    internal static string FailedToCreateAnAudio => GetString(nameof(FailedToCreateAnAudio));
    internal static string FailedToCreateStreetcodeCoordinate => GetString(nameof(FailedToCreateStreetcodeCoordinate));
    internal static string FailedToCreateTeam => GetString(nameof(FailedToCreateTeam));
    internal static string FailedToCreateNews => GetString(nameof(FailedToCreateNews));
    internal static string FailedToDeleteAnAudio => GetString(nameof(FailedToDeleteAnAudio));
    internal static string FailedToDeleteCoordinate => GetString(nameof(FailedToDeleteCoordinate));
    internal static string FailedToDeleteNews => GetString(nameof(FailedToDeleteNews));
    internal static string FailedToDeleteRelatedTerm => GetString(nameof(FailedToDeleteRelatedTerm));
    internal static string FailedToUpdateNews => GetString(nameof(FailedToUpdateNews));
    internal static string FailedToUpdateStreetcodeCoordinate => GetString(nameof(FailedToUpdateStreetcodeCoordinate));
    internal static string NoNewsByEnteredId => GetString(nameof(NoNewsByEnteredId));
    internal static string NoNewsByEnteredUrl => GetString(nameof(NoNewsByEnteredUrl));
    internal static string NoNewsFoundByEnteredId => GetString(nameof(NoNewsFoundByEnteredId));
    internal static string NoPartnerWithSuchId => GetString(nameof(NoPartnerWithSuchId));
    internal static string MissingDefaultConnectionString => GetString(nameof(MissingDefaultConnectionString));
    internal static string RelatedWordAlreadyExists => GetString(nameof(RelatedWordAlreadyExists));
    internal static string TermWithTitleAlreadyExists => GetString(nameof(TermWithTitleAlreadyExists));
    internal static string ThereAreNoNewsInDatabase => GetString(nameof(ThereAreNoNewsInDatabase));
}
