//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streetcode.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Streetcode.BLL.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio MIME type and extension combination is not supported..
        /// </summary>
        public static string AudioMimeTypeAndExtensionNotSupported {
            get {
                return ResourceManager.GetString("AudioMimeTypeAndExtensionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} is required..
        /// </summary>
        public static string Field_Required {
            get {
                return ResourceManager.GetString("Field_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image MIME type and extension combination is not supported..
        /// </summary>
        public static string ImageMimeTypeAndExtensionNotSupported {
            get {
                return ResourceManager.GetString("ImageMimeTypeAndExtensionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} is invalid..
        /// </summary>
        public static string Invalid_Property {
            get {
                return ResourceManager.GetString("Invalid_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude must be between -90 and 90..
        /// </summary>
        public static string LatitudeMustBeBetween {
            get {
                return ResourceManager.GetString("LatitudeMustBeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude must be between -180 and 180..
        /// </summary>
        public static string LongitudeMustBeBetween {
            get {
                return ResourceManager.GetString("LongitudeMustBeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be valid Base64..
        /// </summary>
        public static string MustBeValidBase64 {
            get {
                return ResourceManager.GetString("MustBeValidBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a valid HTTP or HTTPS URL..
        /// </summary>
        public static string MustBeValidHttpUrl {
            get {
                return ResourceManager.GetString("MustBeValidHttpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ID must be greater than 0..
        /// </summary>
        public static string MustBeValidId {
            get {
                return ResourceManager.GetString("MustBeValidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not exceed {1} characters..
        /// </summary>
        public static string MustNotExceedLength {
            get {
                return ResourceManager.GetString("MustNotExceedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must not exceed {0}..
        /// </summary>
        public static string MustNotExceedPaginationLimits {
            get {
                return ResourceManager.GetString("MustNotExceedPaginationLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment amount must be greater than 0..
        /// </summary>
        public static string PaymentGreaterThan_Zero {
            get {
                return ResourceManager.GetString("PaymentGreaterThan_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be greater than 0..
        /// </summary>
        public static string PropertyGreaterThan_Zero {
            get {
                return ResourceManager.GetString("PropertyGreaterThan_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender email must be a valid email address..
        /// </summary>
        public static string SenderMustBeValidEmail {
            get {
                return ResourceManager.GetString("SenderMustBeValidEmail", resourceCulture);
            }
        }
    }
}
